[build]
  base = "."
  command = "npm run build"
  publish = "web"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/app_proxy/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/webhooks/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "netlify/functions" 