# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "promotional-banner-app"
client_id = "YOUR_CLIENT_ID"
application_url = "https://your-app-url.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE_URL"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes"

[auth]
redirect_urls = [
  "https://your-app-url.vercel.app/auth/callback",
  "https://your-app-url.vercel.app/auth/shopify/callback",
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false 