api_version = "2024-01"

[[extensions]]
name = "promotional-banner"
handle = "promotional-banner"
type = "theme_app_extension"

[extensions.settings]
  [[extensions.settings.settings]]
  type = "checkbox"
  id = "enable_banner"
  label = "Enable promotional banner"
  default = true
  
  [[extensions.settings.settings]]
  type = "text"
  id = "banner_text"
  label = "Banner text"
  default = "🎉 Free Shipping on All Orders! 🎉"
  
  [[extensions.settings.settings]]
  type = "color"
  id = "background_color"
  label = "Background color"
  default = "#4CAF50"
  
  [[extensions.settings.settings]]
  type = "color"
  id = "text_color"
  label = "Text color"
  default = "#FFFFFF" 